-- MySQL Script generated by MySQL Workbench
-- Mon May  1 16:12:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssafytrip` DEFAULT CHARACTER SET utf8 ;
USE `ssafytrip` ;

-- -----------------------------------------------------
-- Table `mydb`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`grade` (
  `id` TINYINT(1) NOT NULL,
  `grade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NULL,
  `gender` CHAR(1) NULL,
  `grade_id` TINYINT(1) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `age` INT NULL,
  `join_at` TIMESTAMP NULL,
  `last_login` TIMESTAMP NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_user_grade_idx` (`grade_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_grade`
    FOREIGN KEY (`grade_id`)
    REFERENCES `mydb`.`grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `view_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_board_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_board_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`star`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`star` (
  `board_id` INT NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`board_id`, `user_email`),
  INDEX `fk_board_has_user_user1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_board_has_user_board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_has_user_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_has_user_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `board_id` INT NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `board_id`, `user_email`),
  INDEX `fk_board_has_user_user2_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_board_has_user_board2_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_has_user_board2`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_has_user_user2`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`board_category` (
  `id` INT NOT NULL,
  `board_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_board_category_board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_category_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`attractions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `phone_number_1` INT NULL,
  `phone_number_2` INT NULL,
  `phone_number_3` INT NULL,
  `business_hours` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafytrip`.`rating` (
  `user_email` VARCHAR(45) NOT NULL,
  `attractions_id` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`user_email`, `attractions_id`),
  INDEX `fk_user_has_attractions_attractions1_idx` (`attractions_id` ASC) VISIBLE,
  INDEX `fk_user_has_attractions_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_attractions_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_attractions_attractions1`
    FOREIGN KEY (`attractions_id`)
    REFERENCES `mydb`.`attractions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
